name: workflow to deploy an ARM Template using CLI commands
on: push

# CONFIGURATION
# For help, go to https://github.com/Azure/Actions
#
# Set up the following secrets in your repository:
#   AZURE_CREDENTIALS, REGISTRY_USERNAME, REGISTRY_PASSWORD, AZURE_DEVOPS_TOKEN
# 2. Change these variables for your configuration:
env:
  AZURE_RESOURCE_GROUP: ActionsDemo   # set this to your Azure Resource group's name  
  AZURE_LOCATION: WestEurope

jobs:
  build-and-deploy-to-dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
            
   # Authentication
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS  }}
        
    # Deployment of template
    - name: Azure CLI script to deploy an ARM Template
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          az group create --location ${{ env.AZURE_LOCATION }} --name ${{ env.AZURE_RESOURCE_GROUP }}
          az group deployment create --resource-group ${{ env.AZURE_RESOURCE_GROUP }}${{ env.AZURE_RESOURCE_GROUP }} --template-file $GITHUB_WORKSPACE/azuredeploy.json
